version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  api:
    image: graphql_api:master
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./
    depends_on:
      - db
    ports:
      - 4000:4000
